name: Auto Comment
on:
  pull_request_target:
    types:
      - opened

    branches:
      - main
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: gh pr comment $ISSUE --body "## What type of PR is this:"
        env:
          PR_REQUEST: ${{ github.event.pull_request.html_url }}
