name: Auto Comment
on: [pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: |
            git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
            git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: |
            ## What type of PR is this:
            - [ ] BugFix
            - [ ] Feature
            - [ ] Enhancement
            - [ ] Refactor
            - [ ] UT
            - [ ] Doc
            - [ ] Tool

            ## Checklist:
            - [ ] I have added test cases for my bug fix or my new feature
            - [ ] This pr will affect users' behaviors
            - [ ] This pr needs user documentation (for new or modified features or behaviors)
              - [ ] I have added documentation for my new feature or new function

            ## Bugfix cherry-pick branch check:
            - [ ] I have checked the version labels which the pr will be auto backported to target branch
              - [ ] 3.0
              - [ ] 2.5
              - [ ] 2.4
              - [ ] 2.3
