name: PR COMMENT CHECKER

on:
  issue_comment:
    branches:
      - main
    types:
      - created
      - edited

jobs:
  branch-info-check:
    runs-on: ubuntu-latest
    if: >
       ${{ github.event.issue.pull_request }} &&
       (startsWith(github.event.pull_request.title, '[BugFix]') ||
       startsWith(github.event.pull_request.title, '[Enhancement]')) &&
       !contains(github.event.pull_request.title, 'cherry-pick') &&
       !contains(github.event.pull_request.title, 'backport')
       
    steps:
      - name: add branch-3.0 label
        if: contains(toJson(github.event.comment.body), '[x] 3.0')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: '3.0'
          
      - name: add branch-2.5 label
        if: contains(toJson(github.event.comment.body), '[x] 2.5')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: '2.5'

      - name: remove branch-3.0 label
        if: contains(toJson(github.event.comment.body), '[ ] 3.0') && contains(github.event.pull_request.labels.*.name, '3.0')
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: '3.0'
          
      - name: remove branch-2.5 label
        if: contains(toJson(github.event.comment.body), '[ ] 2.5') && contains(github.event.pull_request.labels.*.name, '2.5')
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: '2.5'
          
      - name: check-done
        if: contains(toJson(github.event.comment.body), '[ ] I have checked the version labels')
        run: |
          echo "You must mark this checkbox - I have checked the version labels which the pr will be auto backported to target branch"
          exit 1
