name: PR CHECKER

on:
  pull_request_review_comment:
    branches:
      - main
    types:
      - created
      - edited
      - deleted

jobs:
  branch-info-check:
    runs-on: ubuntu-latest
    if: >
      (startsWith(github.event.pull_request.title, '[BugFix]') ||
       startsWith(github.event.pull_request.title, '[Enhancement]'))&&
      !contains(github.event.pull_request.title, 'cherry-pick') &&
      !contains(github.event.pull_request.title, 'backport')
    steps:

      - name: add branch-3.0 label
        if: contains(toJson(github.event.pull_request_review_comment.body), '[x] 3.0')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: 'documentation'

      - name: remove branch-3.0 label
        if: contains(toJson(github.event.pull_request.body), '[ ] 3.0') && contains(github.event.pull_request.labels.*.name, '3.0')
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: 'documentation'

      - name: check-done
        if: >
          (startsWith(github.event.pull_request.title, '[BugFix]') ||
           startsWith(github.event.pull_request.title, '[Enhancement]'))&&
          !contains(github.event.pull_request.title, 'cherry-pick') &&
          !contains(github.event.pull_request.title, 'backport') &&
          contains(toJson(github.event.pull_request_review_comment.body), '[ ] I have checked the version labels')
        run: |
          echo "You must mark this checkbox - I have checked the version labels which the pr will be auto backported to target branch"
          exit 1
