name: PR COMMENT CHECKER

on:
  issue_comment:
    branches:
      - main
    types:
      - created
      - edited

jobs:
  branch-info-check:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      - name: add branch-3.0 label
        if: contains(toJson(github.event.comment.body), '[x] 3.0')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: 'documentation'

      - name: remove branch-3.0 label
        if: contains(toJson(github.event.pull_request.body), '[ ] 3.0') && contains(github.event.pull_request.labels.*.name, '3.0')
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: 'documentation'
